variables:
  ARGO_SERVER: 'argo.<AWS_HOSTED_ZONE_NAME>:443'
  ARGO_HTTP1: 'true'  
  ARGO_SECURE: 'true'
  ARGO_NAMESPACE: argo
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"
  BUILDER_IMAGE: "kubefirst/chubbo:0.2"

stages:
  - branch
  - publish
  - development
  - staging
  - release

lint:
  image: "${BUILDER_IMAGE}"
  stage: branch
  only:
    - branches
  except:
    - main
  script:
    - |
      argo submit .argo/npm-run.yaml \
        --generate-name="${CI_PROJECT_NAME}-lint-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p npmScriptName="lint" \
        --wait --log

build:
  image: "${BUILDER_IMAGE}"
  stage: branch
  only:
    - branches
  except:
    - main
  script:
    - |
      argo submit .argo/npm-run.yaml \
        --generate-name="${CI_PROJECT_NAME}-build-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p npmScriptName="build" \
        --wait --log

publish:
  image: "${BUILDER_IMAGE}"
  stage: publish
  only:
    - main
  script:
    - echo "commit sha $CI_COMMIT_SHA"
    - |
      argo submit .argo/publish.yaml \
        --generate-name="${CI_PROJECT_NAME}-publish-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p ciCommitSha="${CI_COMMIT_SHA}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p shortSha="${CI_COMMIT_SHORT_SHA}" \
        --wait --log
            

development:
  image: "${BUILDER_IMAGE}"
  stage: development
  only:
    - main
  script:
    - echo "commit sha $CI_COMMIT_SHA"
    - |
      argo submit .argo/deploy.yaml \
        --generate-name="${CI_PROJECT_NAME}-development-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p ciCommitSha="${CI_COMMIT_SHA}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p environment="development" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p shortSha="${CI_COMMIT_SHORT_SHA}" \
        --wait --log

staging:
  image: "${BUILDER_IMAGE}"
  stage: staging
  only:
    - main
  script:
    - echo "commit sha $CI_COMMIT_SHA"
    - |
      argo submit .argo/deploy.yaml \
        --generate-name="${CI_PROJECT_NAME}-staging-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p ciCommitSha="${CI_COMMIT_SHA}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p environment="staging" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p shortSha="${CI_COMMIT_SHORT_SHA}" \
        --wait --log

release:
  image: "${BUILDER_IMAGE}"
  stage: release
  only:
    - main
  script:
    - echo "commit sha $CI_COMMIT_SHA"
    - |
      argo submit .argo/release.yaml \
        --generate-name="${CI_PROJECT_NAME}-release-${CI_COMMIT_SHORT_SHA}" \
        -p appName="${CI_PROJECT_NAME}" \
        -p ciCommitSha="${CI_COMMIT_SHA}" \
        -p branch="${CI_COMMIT_REF_NAME}" \
        -p environment="production" \
        -p gitRepoUrl="${CI_PROJECT_URL}" \
        -p shortSha="${CI_COMMIT_SHORT_SHA}" \
        --wait --log
