version: "3"

services:
  kubefirst:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./build/dev/Dockerfile
    container_name: kubefirst-dev
    environment:
      TERM: xterm-256color
    volumes:
      - ./:/home/developer/kubefirst
      # AWS credentials are strictly used to provision the Kubefirst in your AWS account
      - $HOME/.aws:/home/developer/.aws
    dns:
      - 208.67.222.222 #Cisco DNS
      - 1.1.1.1 #Cloudflare DNS
      - 1.0.0.1 #Cloudflare DNS
      - 8.8.8.8 #Google DNS
    command: sh -c "./scripts/kubefirst.sh"
    ports:
      - "8080:8080" #Kubefirst console port
      - "8081:8081" #Kubefirst internal api port

