site_name: Kubefirst Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.tabs.link
  logo: img/site/k-ray-light.png
  favicon: img/site/k-ray.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
nav:
  - Home:
    - index.md
    - Kubefirst Platform:
      - Overview: 'kubefirst/overview.md'
      - Local Installation:
        - Install: 'kubefirst/local/install.md'
        - After Install: 'kubefirst/local/after-install.md'
        - GitHub Repositories: 'kubefirst/local/github-repositories.md'
        - Argo CD: 'kubefirst/local/argocd.md'
        - GitOps: 'kubefirst/local/gitops.md'
        - Terraform & Atlantis: 'kubefirst/local/terraform.md'
        - Vault: 'common/vault.md'
        - Metaphor: 'common/metaphor.md'
        - Credit: 'kubefirst/local/credit.md'
        - Destroy: 'kubefirst/local/destroy.md'
      - GitHub Installation:
        - Install: 'kubefirst/github/install.md'
        - After Install: 'kubefirst/github/after-install.md'
        - GitHub Repositories: 'kubefirst/github/github-repositories.md'
        - Argo CD: 'kubefirst/github/argocd.md'
        - GitOps: 'kubefirst/github/gitops.md'
        - Terraform & Atlantis: 'kubefirst/github/terraform.md'
        - Vault: 'common/vault.md'
        - Metaphor: 'common/metaphor.md'
        - Certificates: 'common/certificates.md'
        - Security: 'common/security.md'
        - Credit: 'kubefirst/github/credit.md'
        - Destroy: 'kubefirst/github/destroy.md'
      - GitLab Installation:
        - Install: 'kubefirst/gitlab/install.md'
        - After Install: 'kubefirst/gitlab/after-install.md'
        - Gitlab: 'kubefirst/gitlab/gitlab.md'
        - Gitlab Repositories: 'kubefirst/gitlab/gitlab-repositories.md'
        - Argo CD: 'kubefirst/gitlab/argocd.md'
        - GitOps: 'kubefirst/gitlab/gitops.md'
        - Terraform & Atlantis: 'kubefirst/gitlab/terraform.md'
        - Vault: 'common/vault.md'
        - Metaphor: 'common/metaphor.md'
        - Certificates: 'common/certificates.md'
        - Security: 'common/security.md'
        - Credit: 'kubefirst/gitlab/credit.md'
        - Destroy: 'kubefirst/gitlab/destroy.md'
      - Installer Options:
        - Config: 'kubefirst/installer/config-file.md'
      - FAQ: 'kubefirst/FAQ.md'
    - Tooling:
      - Overview: 'tooling/tooling-overview.md'
      - Argo CD: 'tooling/argocd.md'
      - Argo Workflows: 'tooling/argo.md'
      - CWFT:
        - Overview: 'tooling/argo/cwft-overview.md'
        - cwft-ci: 'tooling/argo/cwft-ci.md'
        - cwft-docker: 'tooling/argo/cwft-docker.md'
        - cwft-git: 'tooling/argo/cwft-git.md'
        - cwft-helm: 'tooling/argo/cwft-helm.md'
        - cwft-npm: 'tooling/argo/cwft-npm.md'
      - AWS CLI: 'tooling/aws-cli.md'
      - Docker: 'tooling/docker.md'
      - Kubectl:  'tooling/kubectl.md'
      - Kubefirst CLI: 'tooling/kubefirst-cli.md'
      - Shell Utilities: 'tooling/shell-utilities.md'
      - Terraform: 'tooling/terraform.md'
      - Vault CLI: 'tooling/vault-cli.md'
    - Community:
      - Community: 'community/index.md'
    - Roadmap:
      - Roadmap: 'roadmap/index.md'
  - Community:
    - Community: 'community/index.md'
  - Roadmap:
    - Roadmap: 'roadmap/index.md'
  - Blog:
    - Blog: 'https://kubefirst.io/blog'
  - Site:
    - Site: 'https://kubefirst.io'

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-QWZQ3YYLL2

repo_url: https://github.com/kubefirst/kubefirst
edit_uri: edit/main/docs/
