site_name: Kubefirst Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
#    - navigation.expand
    - navigation.indexes
    - content.tabs.link
    - navigation.footer
  logo: img/site/k-ray-light.png
  favicon: img/site/k-ray.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
nav:
  - Home:
    - index.md
    - Kubefirst Platform:
      - Overview: 'kubefirst/overview.md'
      - Local Platform:
        - Explore:
          - Install: 'kubefirst/local/install.md' # do not move - marketing site impact
          - Overview: 'kubefirst/local/explore/overview.md'
          - Kubefirst Console: 'kubefirst/local/explore/console.md'
          - Atlantis User Creation: 'kubefirst/local/explore/user-creation.md'
          - Metaphor: 'kubefirst/local/explore/metaphor.md'
          - GitHub Repositories: 'kubefirst/local/explore/github-repositories.md'  
        - Limitations: 'kubefirst/local/limitations.md'
        - Destroy: 'kubefirst/local/destroy.md'
      - Civo Platform:
        - Getting Started:
          - Install: 'kubefirst/civo/install.md' # do not move - marketing site impact
          - Overview: 'kubefirst/civo/getting-started/overview.md'
          - GitHub Repositories: 'kubefirst/civo/getting-started/github-repositories.md'   
          - Onboard Users: 'kubefirst/civo/getting-started/user-creation.md'
          - Metaphor: 'kubefirst/civo/getting-started/metaphor.md'
        - Explore:
          - Argo CD: 'explore/argocd.md'
          - GitOps: 'explore/gitops.md'
          - Terraform & Atlantis: 'explore/terraform.md'
          - Vault: 'explore/vault.md'
        - Destroy: 'kubefirst/civo/destroy.md'
      - AWS Platform (GitHub):
        - Getting Started:
          - Install: 'kubefirst/github/install.md' # do not move - marketing site impact
          - GitHub Repositories: 'kubefirst/github/github-repositories.md'
          - Overview: 'kubefirst/github/overview.md'
        - Explore:
          - Argo CD: 'explore/argocd.md'
          - GitOps: 'explore/gitops.md'
          - Terraform & Atlantis: 'explore/terraform.md'
          - Vault: 'explore/vault.md'
        - Advanced:
          - Security: explore/security.md
          - Certificates: 'explore/certificates.md'
          - GitHub Token: 'explore/github-token.md'
          - Metaphor: 'explore/metaphor.md'
        - Destroy: 'kubefirst/github/destroy.md'
      - AWS Platform (GitLab):
        - Getting Started:
          - Install: 'kubefirst/gitlab/install.md' # do not move - marketing site impact
          - Overview: 'kubefirst/gitlab/explore.md'
          - GitLab: 'kubefirst/gitlab/gitlab.md'
          - GitLab Repositories: 'kubefirst/gitlab/gitlab-repositories.md'
        - Explore:
          - Argo CD: 'explore/argocd.md'
          - GitOps: 'explore/gitops.md'
          - Terraform & Atlantis: 'explore/terraform.md'
          - Vault: 'explore/vault.md'
        - Advanced:
          - Security: explore/security.md
          - Certificates: 'explore/certificates.md'
          - Metaphor: 'explore/metaphor.md'
        - Destroy: 'kubefirst/gitlab/destroy.md'
      - Installer Options:
        - Config: 'kubefirst/installer/config-file.md'
        - OpenTelemetry: 'explore/open-telemetry.md'
      - FAQ: 'kubefirst/FAQ.md'
      - Credit: 'kubefirst/credit.md'
  - Community:
    - Community: 'community/index.md'
  - Roadmap:
    - Roadmap: 'roadmap/index.md'
  - Blog:
    - Blog: 'https://kubefirst.io/blog'
  - Site:
    - Site: 'https://kubefirst.io'

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-QWZQ3YYLL2

repo_url: https://github.com/kubefirst/kubefirst
edit_uri: edit/main/docs/
